LTO_ENABLE = yes
COMBO_ENABLE = yes
OLED_ENABLE = yes
ENCODER_ENABLE = yes
WPM_ENABLE = yes

CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no 
MAGIC_ENABLE = no